"""rename address

Revision ID: 234978bef0ac
Revises: 885e06fe37d0
Create Date: 2024-08-15 09:42:23.440512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '234978bef0ac'
down_revision = '885e06fe37d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
      op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
     op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
