"""rebname department

Revision ID: 885e06fe37d0
Revises: dcf1f565c9f4
Create Date: 2024-08-15 09:36:22.658613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '885e06fe37d0'
down_revision = 'dcf1f565c9f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
     op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    
    # ### end Alembic commands ###
